{"name": "test_handle_base_exceptions_async_other_exception", "status": "passed", "attachments": [{"name": "log", "source": "aabfb482-6196-445a-8dc1-370c1b94727f-attachment.txt", "type": "text/plain"}], "start": 1753152649964, "stop": 1753152649966, "uuid": "0bfe77be-e1be-4689-847e-22bbb53f4d51", "historyId": "f2e927311efa5536591284318d72132b", "testCaseId": "f2e927311efa5536591284318d72132b", "fullName": "tests.unit.utils.test_decorator#test_handle_base_exceptions_async_other_exception", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "parentSuite", "value": "tests.unit.utils"}, {"name": "suite", "value": "test_decorator"}, {"name": "host", "value": "pkrvmq0rgcvqdmg"}, {"name": "thread", "value": "2923-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.utils.test_decorator"}]}